### ISSUE TITLE
Malformed JSON on Official devices.json

### ISSUE THREAD

**Issue by sanjithacks** [ProjectBlaze/official_devices#90] opened 2023-12-07 09:22 UTC
# Malformed JSON on Official devices.json

Invalid JSON format, on "xda": "null" for Realme Devices (require a comma) from id "2":  to "7": 

## Invalid JSON ❌

```json
{
"name": "Realme X3",
"codename": "RMX2081",
"maintainer": "@Ak_jagxz",
"xda": "null"   //⚠️This line need an ending/closing ","
"telegram": "https://t.me/Ak_builds",
"download": "null"
}
```

## Valid JSON ✅

```json
{
"name": "Realme X3",
"codename": "RMX2081",
"maintainer": "@Ak_jagxz",
"xda": "null",   //✅ Add closing comma ","
"telegram": "https://t.me/Ak_builds",
"download": "null"
}
```

- https://github.com/ProjectBlaze/official_devices/blob/77a08a0e424c9f2f14ac98ab23043bb224b23887/devices.json#L25
- https://github.com/ProjectBlaze/official_devices/blob/77a08a0e424c9f2f14ac98ab23043bb224b23887/devices.json#L33
- https://github.com/ProjectBlaze/official_devices/blob/77a08a0e424c9f2f14ac98ab23043bb224b23887/devices.json#L41
- https://github.com/ProjectBlaze/official_devices/blob/77a08a0e424c9f2f14ac98ab23043bb224b23887/devices.json#L49
- https://github.com/ProjectBlaze/official_devices/blob/77a08a0e424c9f2f14ac98ab23043bb224b23887/devices.json#L57
- https://github.com/ProjectBlaze/official_devices/blob/77a08a0e424c9f2f14ac98ab23043bb224b23887/devices.json#L65

**Comment by afterallafk** [comment] 2023-12-16 13:53
Thank you very much the issue is now fixed.

**Closed as completed by afterallafk** 2023-12-16 13:53 UTC
